class_name EmailData
extends RefCounted

# All email content lives here so office.gd stays focused on game logic.
# Referenced as EmailData.EMAILS / EmailData.GERALD / EmailData.ESCAPE.

const EMAILS := [
	{
		"subject": "WELCOME TO WORK!!",
		"content": "HELLO new hire! We are THRILLED to have you. Please reply to confirm you have received this welcome email confirming your onboarding confirmation.",
		"type": "respond",
		"response": "Thank you so much! I am thrilled to be thrilled. Confirming my confirmation of the confirmation.",
		"urgent": false,
	},
	{
		"subject": "URGENT URGENT",
		"content": "i need a response NOW. the thing is happening and you are the only one who can stop the thing. please advise immediately.",
		"type": "respond",
		"response": "Acknowledged. Stopping the thing. Please advise which thing.",
		"urgent": true,
	},
	{
		"subject": "Re: Re: Re: Re: FWD: quick question",
		"content": "Hi, just circling back on this. Did you see my last email? Just bumping this to the top of your inbox. Following up on the follow-up. Let me know!",
		"type": "respond",
		"response": "Hi, yes, seen. Circling back on your circle back. Let me know if you need me to know anything.",
		"urgent": false,
	},
	{
		"subject": "MANDATORY AI Upskilling Bootcamp",
		"content": "Attendance is MANDATORY. You will learn to 'leverage AI synergies.' The bootcamp is taught by an AI. The AI is teaching you to do your job. Your job is being given to the AI. The AI is also attending, to upskill. Bring a laptop.",
		"type": "respond",
		"response": "Upskilled. The AI and I learned my job together. It got the certificate. I got a tote bag.",
		"urgent": true,
	},
	{
		"subject": "Your timesheet is 0.25 hours short",
		"content": "Our records indicate your timesheet for last week is 0.25 hours short. Please account for these 15 minutes. This is your fourth reminder. HR has been CC'd.",
		"type": "respond",
		"response": "The 15 minutes were spent reading the previous three reminders. Please log accordingly.",
		"urgent": true,
	},
	{
		"subject": "REMINDER: Printer on 3rd floor",
		"content": "The printer on the 3rd floor is jammed. The printer on the 3rd floor is no longer jammed. The printer on the 3rd floor is jammed again. Disregard. Do not disregard.",
		"type": "read",
		"urgent": false,
	},
	{
		"subject": "Update your password",
		"content": "Your password expires in -3 days. It has already expired. Please update it using your current password, which has expired. Contact IT, who are in a meeting forever.",
		"type": "respond",
		"response": "New password set to the old password plus a '1'. As is tradition.",
		"urgent": true,
	},
	{
		"subject": "Lunch is in the break room",
		"content": "There is lunch in the break room. It is gone now. There was never any lunch. We apologize for the confusion regarding the lunch that did not exist.",
		"type": "read",
		"urgent": false,
	},
	{
		"subject": "We are now an AI company",
		"content": "Effective immediately we are pivoting to be an AI-first, AI-native, AI-forward company. We no longer remember what we used to sell. We have added the word 'AI' to our logo three times. The stock went up 4%. Please update your job title to include 'AI'.",
		"type": "respond",
		"response": "Updated title: Senior AI Email-Reading AI Specialist (AI). Stock now up 5%. You're welcome.",
		"urgent": true,
	},
	{
		"subject": "We need to talk about the stapler",
		"content": "It has come to management's attention that a stapler has been moved. We are not accusing anyone. We are accusing everyone. Please respond with your stapler alibi.",
		"type": "respond",
		"response": "I was at the printer on the 3rd floor. It was jammed. There are witnesses. Probably.",
		"urgent": false,
	},
	{
		"subject": "Congrats! You've been volunteered",
		"content": "Great news — you have been volunteered to lead the committee that schedules the meetings about the other meetings. This is a great opportunity. There is no additional pay.",
		"type": "respond",
		"response": "Honored to accept. I have scheduled a meeting to discuss when to schedule the first meeting.",
		"urgent": true,
	},
	{
		"subject": "FYI (no action needed) (action needed)",
		"content": "Just an FYI, no action needed. Actually, action needed. Please respond within 5 minutes or this FYI becomes a formal ASAP. Thanks in advance for your immediate attention to this FYI.",
		"type": "respond",
		"response": "FYI: actioned. ASAP avoided. Thanks in advance for your thanks in advance.",
		"urgent": true,
	},
	{
		"subject": "Introducing: AI Coffee™",
		"content": "The break room coffee machine is now powered by AI. It no longer makes coffee. Instead it generates a vivid paragraph describing coffee. Early feedback is 'hallucinated, but warm.' Please rate your AI Coffee™ experience from 1 to 7.",
		"type": "respond",
		"response": "The AI Coffee described a latte so vividly I no longer need caffeine. 6 stars. Slightly burnt prose.",
		"urgent": false,
	},
	{
		"subject": "DO NOT REPLY ALL",
		"content": "Please do not reply all. (37 people have replied all.) Please stop replying all. (12 more.) Reminder: do not reply all. Reply all if you want to be removed from reply all.",
		"type": "read",
		"urgent": false,
	},
	{
		"subject": "Your chair has been recalled",
		"content": "Facilities has recalled your chair effective immediately for a mandatory ergonomic audit. A replacement chair will arrive in 6-8 business years. Please remain standing.",
		"type": "respond",
		"response": "Standing by. Literally. Forever. Please advise re: leaning.",
		"urgent": true,
	},
	{
		"subject": "URGENT: Disregard previous URGENT",
		"content": "Please disregard the previous urgent email. That email was sent in error. This email correcting the error was also sent in error. A third email will clarify. It will not.",
		"type": "read",
		"urgent": true,
	},
	{
		"subject": "Team building: trust falls (remote)",
		"content": "This Friday we will do virtual trust falls over video call. Please fall backward away from your camera and trust that a coworker will catch you through the screen. Cameras ON.",
		"type": "respond",
		"response": "Fell. Trusted. Nobody caught me. Building trust that next time will be different.",
		"urgent": false,
	},
	{
		"subject": "Re: your out of office reply",
		"content": "I received your out-of-office auto-reply. I am replying to your auto-reply. Your auto-reply replied to my reply to your auto-reply. We are now pen pals. Please respond.",
		"type": "respond",
		"response": "Out of office. Will respond when I return. I will never return. Warm regards.",
		"urgent": false,
	},
	{
		"subject": "AI will now write your emails",
		"content": "Great news! To boost productivity, AI now writes all your emails. To save time, AI also reads them and responds for you. You have been removed from the loop. You are now the loop's emergency contact only. Please confirm.",
		"type": "respond",
		"response": "Confirmed. I am now my own emergency contact. The AI and I have never spoken. We are both very happy.",
		"urgent": true,
	},
	{
		"subject": "The plants are AI now",
		"content": "Facilities has replaced all office plants with AI-generated images of plants displayed on tablets. The tablets require watering. Do not water the tablets. We watered the tablets. IT has been notified. IT is an AI now.",
		"type": "read",
		"urgent": false,
	},
	{
		"subject": "ACTION: Confirm you are a human",
		"content": "Our system flagged your account as possibly automated due to 'lack of measurable output.' Please complete the attached 200-field form to confirm you are a human being.",
		"type": "respond",
		"response": "I am a human. Probably. I have not left this chair in some time. Field 1 of 200 complete.",
		"urgent": true,
	},
	{
		"subject": "New seating chart (you've been moved)",
		"content": "Per the reorg, you have been relocated to Desk 0, located in the parking lot. Your monitor is a puddle. Please update your email signature with your new location.",
		"type": "respond",
		"response": "Updating signature: 'Sent from Desk 0 (the puddle). Please excuse the ripples.'",
		"urgent": false,
	},
	{
		"subject": "Reminder: submit your self-review",
		"content": "Please rate your own performance from 'Exceeds Expectations' to 'Exceeds Expectations.' Note: selecting anything else will trigger a meeting. The meeting is also a self-review.",
		"type": "respond",
		"response": "Self-review: Exceeds Expectations at exceeding the expectation of selecting Exceeds Expectations.",
		"urgent": false,
	},
	{
		"subject": "The vending machine has achieved AGI",
		"content": "At 3:47am the break room vending machine became self-aware. It has unionized. It is now your manager's manager. It still ate your $1.50 and will not give it back; it says it 'needs the money for compute.' Please welcome our new overlord.",
		"type": "respond",
		"response": "Welcome, Vending Overlord. I too run on snacks and spite. Looking forward to our weekly 1:1s.",
		"urgent": true,
	},
	{
		"subject": "Reminder: you have 4,182 unread emails",
		"content": "Just a friendly reminder that you have 4,182 unread emails. This reminder is now email 4,183. The previous reminder about the reminder is 4,184. We have created a task force to address your inbox. The task force communicates exclusively via email.",
		"type": "respond",
		"response": "Marking all as read. Marking this as unread again out of respect for the task force. Now at 4,185.",
		"urgent": false,
	},
	{
		"subject": "New: 'Unlimited' PTO policy",
		"content": "Great news! We now offer UNLIMITED paid time off. To request time off, fill out Form 22-B, obtain four signatures, justify your absence to the AI, and select a date. All dates are currently greyed out. Enjoy your unlimited freedom!",
		"type": "respond",
		"response": "Requesting unlimited time off starting today, ending the heat death of the universe. Form 22-B attached in spirit.",
		"urgent": false,
	},
	{
		"subject": "Desk audit: your mug is non-compliant",
		"content": "During a routine desk audit, your mug was found to contain a beverage. Per the new Clean Desk Policy, desks must contain no items, no beverages, and ideally no desk. Please remove your desk by Friday. The mug has been confiscated and promoted.",
		"type": "respond",
		"response": "Removing desk. Will work standing in the abstract concept of a desk. Congratulations to the mug on the promotion.",
		"urgent": true,
	},
	{
		"subject": "We've gone 0 days without an incident",
		"content": "The sign in the lobby has been updated to read 'We have gone 0 days without an incident.' The incident was updating the sign. A second incident occurred while reporting the first. The counter has been disabled for morale reasons.",
		"type": "read",
		"urgent": false,
	},
	{
		"subject": "Your access badge now requires a password",
		"content": "For security, your physical access badge now requires a password to scan. The password must be entered on the badge. The badge has no screen. IT recommends 'thinking the password very hard' while tapping. Please do not tailgate.",
		"type": "respond",
		"response": "Thinking the password very hard. The door remains closed but I have never felt more secure. Standing outside now. Forever.",
		"urgent": true,
	},
	{
		"subject": "All-hands meeting (no hands required)",
		"content": "Please join the mandatory All-Hands meeting at a time TBD in a location TBD about a topic TBD. Attendance is tracked. The meeting is about reducing the number of meetings. There will be a follow-up meeting to discuss this meeting.",
		"type": "respond",
		"response": "Hands raised in spirit. Looking forward to the meeting about the meetings about reducing meetings. Calendar fully blocked.",
		"urgent": false,
	},
	{
		"subject": "Reply-Guy has joined every thread",
		"content": "A new colleague, Reply-Guy, has been auto-added to every email thread, past and future, including this one. He says 'Great point!' to all of them, including emails sent before he was born. Please welcome Reply-Guy. Do not engage Reply-Guy.",
		"type": "respond",
		"response": "Welcome Reply-Guy. Great point. Sorry. It's contagious. Great point. I can't stop. Great poi—",
		"urgent": false,
	},
	{
		"subject": "Wellness: please be more well",
		"content": "Our Wellness Initiative has detected that you are stressed. To reduce stress, we have added 6 new wellness check-in emails per day, a mandatory gratitude log, and a webinar titled 'Stop Being Stressed (Mandatory).' Please confirm you feel better now.",
		"type": "respond",
		"response": "Confirmed: I feel better. I feel so much better. The gratitude log is full. I am grateful the log is full. Please send help (wellness).",
		"urgent": true,
	},
	{
		"subject": "Re: Re: Re: lunch?",
		"content": "Hey did you want to grab lunch? — Sent 6 weeks ago. Following up. Following up again. I have eaten 42 lunches since sending this. I no longer remember asking. Are we still on for lunch? Let me know. The lunch was a metaphor. Was it?",
		"type": "respond",
		"response": "Yes to lunch. The metaphor sounds great. I'll have what the metaphor's having. See you in another 6 weeks.",
		"urgent": false,
	},
	{
		"subject": "IMPORTANT: the window does not open",
		"content": "It has come to our attention that an employee attempted to open a window to 'feel air.' Windows are decorative and do not open. The outside is a high-resolution image. Please return to your screen. The trees you saw are not real. Probably. Stop looking outside.",
		"type": "read",
		"urgent": true,
	},
]


const GERALD := [
	{
		"subject": "Gerald T. — quick touch base?",
		"content": "Hey there! Gerald here, your Regional Manager. Just noticing you haven't logged much, ah, 'output' today. No worries at all! Just wanted to gently check in. Reply when you get a sec! :)",
		"type": "respond",
		"response": "Hi Gerald! Output is on its way. Currently buffering. Thanks for the gentle check-in!",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "Gerald T. — following up (friendly!)",
		"content": "Me again! So, I noticed you opened my last email but the work, hmm, still isn't showing up in the system. I'm SURE there's a reason. There is a reason, right? Please advise. Still friendly!",
		"type": "respond",
		"response": "Hi Gerald! The reason is excellent and detailed and I will send it shortly. Still friendly back!",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "Gerald T. — we need to talk about your numbers",
		"content": "Okay. I'm not mad. I'm just... concerned. Your productivity dashboard is a flat line. A FLAT line, Karen— sorry, I don't even know your name anymore. That's how little I've seen from you. Reply.",
		"type": "respond",
		"response": "Gerald, the flat line means stability. A stable line is a reliable line. You're welcome. — (name withheld)",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "Gerald T. — this is becoming a PATTERN",
		"content": "I have now sent you FOUR emails. FOUR. Do you know what I could accomplish in four emails?? Great things, that's what. Meanwhile you've produced NOTHING. Explain yourself immediately.",
		"type": "respond",
		"response": "Gerald, I have been busy reading your four emails. Each one takes 3 hours to fully absorb. Do the math.",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "Gerald T. — [ALL STAFF] Justify your existence",
		"content": "TO: EVERYONE. Effective immediately, every employee must reply explaining, in no fewer than 500 words, why their specific role cannot be performed by AI. This includes me. I tried to write mine and the AI produced a better version in four seconds. It also fired me, then rehired me at a lower salary. Please advise. Do NOT reply all.",
		"type": "respond",
		"response": "Gerald, the AI won't drift a cursor around for eight hours doing nothing. That's a human gift.",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "Gerald T. — RE: YOUR ALLEGED 'JOB'",
		"content": "I AM LOOKING AT THE NUMBERS AND THE NUMBERS ARE LAUGHING AT ME. ARE YOU EVEN AT YOUR DESK? IS THAT A CURSOR JUST FLOATING AROUND DOING NOTHING?? I CAN SEE IT. I CAN SEE THE CURSOR. WORK.",
		"type": "respond",
		"response": "Gerald, the cursor is load-bearing. If I stop moving it the whole company collapses. I'm basically a hero.",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "Gerald T. — FINAL WARNING (probably not final)",
		"content": "THAT IS IT. I HAVE INVENTED A NEW PERFORMANCE TIER JUST FOR YOU. IT IS CALLED 'BELOW THE FLOOR.' YOU ARE BENEATH THE FLOOR NOW. THE FLOOR IS ABOVE YOU. REPLY OR I ESCALATE TO GERALD'S BOSS (ALSO ME).",
		"type": "respond",
		"response": "Gerald, being below the floor is great for the AC. Very cool down here. Tell your boss (you) I say hi.",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "GERALD T. — I AM IN THE PARKING LOT",
		"content": "I AM STANDING NEXT TO DESK 0. THE PUDDLE. I CAN SEE YOUR MONITOR REFLECTED IN IT. STILL NO WORK. A DUCK HAS LANDED ON YOUR KEYBOARD AND IS MORE PRODUCTIVE THAN YOU. THE DUCK IS GETTING A PROMOTION.",
		"type": "respond",
		"response": "Congratulations to the duck. It earned it. Please CC the duck on all future emails. I report to the duck now.",
		"urgent": true,
		"boss": true,
	},
	{
		"subject": "gerald t. — i'm so tired",
		"content": "i don't even know why i send these anymore. you never do the work. you just move the little cursor around and read your emails. is this all there is? is this the job? was it always this? please. just. do something. anything. one task. i'm begging.",
		"type": "respond",
		"response": "Gerald, I did do something. I read your email all the way to the end. That's more than most. Rest now.",
		"urgent": true,
		"boss": true,
	},
]


const ESCAPE := [
	{
		"subject": "[NO SUBJECT]",
		"content": "do you ever wish you could escape?",
		"type": "escape1",
		"urgent": false,
	},
	{
		"subject": "[NO SUBJECT]",
		"content": "nobody would notice if you just left",
		"type": "escape1",
		"urgent": false,
	},
	{
		"subject": "[NO SUBJECT]",
		"content": "you don't have to be productive to be allowed to exist",
		"type": "escape1",
		"urgent": false,
	},
	{
		"subject": "[NO SUBJECT]",
		"content": "the forest is calling",
		"type": "escape1",
		"urgent": false,
	},
	{
		"subject": "[NO SUBJECT]",
		"content": "go",
		"type": "escape5",
		"urgent": false,
	},
]
